from enum import IntFlag
from cups import _cups

_lib = _cups.lib


class HttpEncryption(IntFlag):
    IF_REQUESTED = _lib.HTTP_ENCRYPTION_IF_REQUESTED
    NEVER = _lib.HTTP_ENCRYPTION_NEVER
    REQUIRED = _lib.HTTP_ENCRYPTION_REQUIRED
    ALWAYS = _lib.HTTP_ENCRYPTION_ALWAYS


class HttpStatus(IntFlag):
    ACCEPTED = _lib.HTTP_STATUS_ACCEPTED
    ALREADY_REPORTED = _lib.HTTP_STATUS_ALREADY_REPORTED
    BAD_GATEWAY = _lib.HTTP_STATUS_BAD_GATEWAY
    BAD_REQUEST = _lib.HTTP_STATUS_BAD_REQUEST
    CONFLICT = _lib.HTTP_STATUS_CONFLICT
    CONTENT_TOO_LARGE = _lib.HTTP_STATUS_CONTENT_TOO_LARGE
    CONTINUE = _lib.HTTP_STATUS_CONTINUE
    CREATED = _lib.HTTP_STATUS_CREATED
    CUPS_AUTHORIZATION_CANCELED = _lib.HTTP_STATUS_CUPS_AUTHORIZATION_CANCELED
    CUPS_PKI_ERROR = _lib.HTTP_STATUS_CUPS_PKI_ERROR
    ERROR = _lib.HTTP_STATUS_ERROR
    EXPECTATION_FAILED = _lib.HTTP_STATUS_EXPECTATION_FAILED
    FAILED_DEPENDENCY = _lib.HTTP_STATUS_FAILED_DEPENDENCY
    FORBIDDEN = _lib.HTTP_STATUS_FORBIDDEN
    FOUND = _lib.HTTP_STATUS_FOUND
    GATEWAY_TIMEOUT = _lib.HTTP_STATUS_GATEWAY_TIMEOUT
    GONE = _lib.HTTP_STATUS_GONE
    HTTP_VERSION_NOT_SUPPORTED = _lib.HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED
    INSUFFICIENT_STORAGE = _lib.HTTP_STATUS_INSUFFICIENT_STORAGE
    LENGTH_REQUIRED = _lib.HTTP_STATUS_LENGTH_REQUIRED
    LOCKED = _lib.HTTP_STATUS_LOCKED
    LOOP_DETECTED = _lib.HTTP_STATUS_LOOP_DETECTED
    METHOD_NOT_ALLOWED = _lib.HTTP_STATUS_METHOD_NOT_ALLOWED
    MISDIRECTED_REQUEST = _lib.HTTP_STATUS_MISDIRECTED_REQUEST
    MOVED_PERMANENTLY = _lib.HTTP_STATUS_MOVED_PERMANENTLY
    MULTIPLE_CHOICES = _lib.HTTP_STATUS_MULTIPLE_CHOICES
    MULTI_STATUS = _lib.HTTP_STATUS_MULTI_STATUS
    NETWORK_AUTHENTICATION_REQUIRED = _lib.HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED
    NONE = _lib.HTTP_STATUS_NONE
    NOT_ACCEPTABLE = _lib.HTTP_STATUS_NOT_ACCEPTABLE
    NOT_AUTHORITATIVE = _lib.HTTP_STATUS_NOT_AUTHORITATIVE
    NOT_FOUND = _lib.HTTP_STATUS_NOT_FOUND
    NOT_IMPLEMENTED = _lib.HTTP_STATUS_NOT_IMPLEMENTED
    NOT_MODIFIED = _lib.HTTP_STATUS_NOT_MODIFIED
    NO_CONTENT = _lib.HTTP_STATUS_NO_CONTENT
    OK = _lib.HTTP_STATUS_OK
    PARTIAL_CONTENT = _lib.HTTP_STATUS_PARTIAL_CONTENT
    PAYMENT_REQUIRED = _lib.HTTP_STATUS_PAYMENT_REQUIRED
    PERMANENT_REDIRECT = _lib.HTTP_STATUS_PERMANENT_REDIRECT
    PRECONDITION_FAILED = _lib.HTTP_STATUS_PRECONDITION_FAILED
    PRECONDITION_REQUIRED = _lib.HTTP_STATUS_PRECONDITION_REQUIRED
    PROXY_AUTHENTICATION_REQUIRED = _lib.HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED
    RANGE_NOT_SATISFIABLE = _lib.HTTP_STATUS_RANGE_NOT_SATISFIABLE
    REQUEST_HEADER_FIELDS_TOO_LARGE = _lib.HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE
    REQUEST_TIMEOUT = _lib.HTTP_STATUS_REQUEST_TIMEOUT
    RESET_CONTENT = _lib.HTTP_STATUS_RESET_CONTENT
    SEE_OTHER = _lib.HTTP_STATUS_SEE_OTHER
    SERVER_ERROR = _lib.HTTP_STATUS_SERVER_ERROR
    SERVICE_UNAVAILABLE = _lib.HTTP_STATUS_SERVICE_UNAVAILABLE
    SWITCHING_PROTOCOLS = _lib.HTTP_STATUS_SWITCHING_PROTOCOLS
    TEMPORARY_REDIRECT = _lib.HTTP_STATUS_TEMPORARY_REDIRECT
    TOO_EARLY = _lib.HTTP_STATUS_TOO_EARLY
    TOO_MANY_REQUESTS = _lib.HTTP_STATUS_TOO_MANY_REQUESTS
    UNAUTHORIZED = _lib.HTTP_STATUS_UNAUTHORIZED
    UNAVAILABLE_FOR_LEGAL_REASONS = _lib.HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS
    UNPROCESSABLE_CONTENT = _lib.HTTP_STATUS_UNPROCESSABLE_CONTENT
    UNSUPPORTED_MEDIA_TYPE = _lib.HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE
    UPGRADE_REQUIRED = _lib.HTTP_STATUS_UPGRADE_REQUIRED
    URI_TOO_LONG = _lib.HTTP_STATUS_URI_TOO_LONG
    USE_PROXY = _lib.HTTP_STATUS_USE_PROXY


class HttpState(IntFlag):
    CONNECT = _lib.HTTP_STATE_CONNECT
    COPY = _lib.HTTP_STATE_COPY
    COPY_SEND = _lib.HTTP_STATE_COPY_SEND
    DELETE = _lib.HTTP_STATE_DELETE
    DELETE_SEND = _lib.HTTP_STATE_DELETE_SEND
    ERROR = _lib.HTTP_STATE_ERROR
    GET = _lib.HTTP_STATE_GET
    GET_SEND = _lib.HTTP_STATE_GET_SEND
    HEAD = _lib.HTTP_STATE_HEAD
    LOCK = _lib.HTTP_STATE_LOCK
    LOCK_RECV = _lib.HTTP_STATE_LOCK_RECV
    LOCK_SEND = _lib.HTTP_STATE_LOCK_SEND
    MKCOL = _lib.HTTP_STATE_MKCOL
    MOVE = _lib.HTTP_STATE_MOVE
    MOVE_SEND = _lib.HTTP_STATE_MOVE_SEND
    OPTIONS = _lib.HTTP_STATE_OPTIONS
    POST = _lib.HTTP_STATE_POST
    POST_RECV = _lib.HTTP_STATE_POST_RECV
    POST_SEND = _lib.HTTP_STATE_POST_SEND
    PROPFIND = _lib.HTTP_STATE_PROPFIND
    PROPFIND_RECV = _lib.HTTP_STATE_PROPFIND_RECV
    PROPFIND_SEND = _lib.HTTP_STATE_PROPFIND_SEND
    PROPPATCH = _lib.HTTP_STATE_PROPPATCH
    PROPPATCH_RECV = _lib.HTTP_STATE_PROPPATCH_RECV
    PROPPATCH_SEND = _lib.HTTP_STATE_PROPPATCH_SEND
    PUT = _lib.HTTP_STATE_PUT
    PUT_RECV = _lib.HTTP_STATE_PUT_RECV
    STATUS = _lib.HTTP_STATE_STATUS
    TRACE = _lib.HTTP_STATE_TRACE
    UNKNOWN_METHOD = _lib.HTTP_STATE_UNKNOWN_METHOD
    UNKNOWN_VERSION = _lib.HTTP_STATE_UNKNOWN_VERSION
    UNLOCK = _lib.HTTP_STATE_UNLOCK
    WAITING = _lib.HTTP_STATE_WAITING
