from enum import IntFlag

from cups import _cups
from cups.utils import _bytes_to_value

_lib = _cups.lib


class HttpEncryption(IntFlag):
    IF_REQUESTED = _lib.HTTP_ENCRYPTION_IF_REQUESTED
    NEVER = _lib.HTTP_ENCRYPTION_NEVER
    REQUIRED = _lib.HTTP_ENCRYPTION_REQUIRED
    ALWAYS = _lib.HTTP_ENCRYPTION_ALWAYS


class HttpStatus(IntFlag):
    ACCEPTED = _lib.HTTP_STATUS_ACCEPTED
    ALREADY_REPORTED = _lib.HTTP_STATUS_ALREADY_REPORTED
    BAD_GATEWAY = _lib.HTTP_STATUS_BAD_GATEWAY
    BAD_REQUEST = _lib.HTTP_STATUS_BAD_REQUEST
    CONFLICT = _lib.HTTP_STATUS_CONFLICT
    CONTENT_TOO_LARGE = _lib.HTTP_STATUS_CONTENT_TOO_LARGE
    CONTINUE = _lib.HTTP_STATUS_CONTINUE
    CREATED = _lib.HTTP_STATUS_CREATED
    CUPS_AUTHORIZATION_CANCELED = _lib.HTTP_STATUS_CUPS_AUTHORIZATION_CANCELED
    CUPS_PKI_ERROR = _lib.HTTP_STATUS_CUPS_PKI_ERROR
    ERROR = _lib.HTTP_STATUS_ERROR
    EXPECTATION_FAILED = _lib.HTTP_STATUS_EXPECTATION_FAILED
    FAILED_DEPENDENCY = _lib.HTTP_STATUS_FAILED_DEPENDENCY
    FORBIDDEN = _lib.HTTP_STATUS_FORBIDDEN
    FOUND = _lib.HTTP_STATUS_FOUND
    GATEWAY_TIMEOUT = _lib.HTTP_STATUS_GATEWAY_TIMEOUT
    GONE = _lib.HTTP_STATUS_GONE
    HTTP_VERSION_NOT_SUPPORTED = _lib.HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED
    INSUFFICIENT_STORAGE = _lib.HTTP_STATUS_INSUFFICIENT_STORAGE
    LENGTH_REQUIRED = _lib.HTTP_STATUS_LENGTH_REQUIRED
    LOCKED = _lib.HTTP_STATUS_LOCKED
    LOOP_DETECTED = _lib.HTTP_STATUS_LOOP_DETECTED
    METHOD_NOT_ALLOWED = _lib.HTTP_STATUS_METHOD_NOT_ALLOWED
    MISDIRECTED_REQUEST = _lib.HTTP_STATUS_MISDIRECTED_REQUEST
    MOVED_PERMANENTLY = _lib.HTTP_STATUS_MOVED_PERMANENTLY
    MULTIPLE_CHOICES = _lib.HTTP_STATUS_MULTIPLE_CHOICES
    MULTI_STATUS = _lib.HTTP_STATUS_MULTI_STATUS
    NETWORK_AUTHENTICATION_REQUIRED = _lib.HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED
    NONE = _lib.HTTP_STATUS_NONE
    NOT_ACCEPTABLE = _lib.HTTP_STATUS_NOT_ACCEPTABLE
    NOT_AUTHORITATIVE = _lib.HTTP_STATUS_NOT_AUTHORITATIVE
    NOT_FOUND = _lib.HTTP_STATUS_NOT_FOUND
    NOT_IMPLEMENTED = _lib.HTTP_STATUS_NOT_IMPLEMENTED
    NOT_MODIFIED = _lib.HTTP_STATUS_NOT_MODIFIED
    NO_CONTENT = _lib.HTTP_STATUS_NO_CONTENT
    OK = _lib.HTTP_STATUS_OK
    PARTIAL_CONTENT = _lib.HTTP_STATUS_PARTIAL_CONTENT
    PAYMENT_REQUIRED = _lib.HTTP_STATUS_PAYMENT_REQUIRED
    PERMANENT_REDIRECT = _lib.HTTP_STATUS_PERMANENT_REDIRECT
    PRECONDITION_FAILED = _lib.HTTP_STATUS_PRECONDITION_FAILED
    PRECONDITION_REQUIRED = _lib.HTTP_STATUS_PRECONDITION_REQUIRED
    PROXY_AUTHENTICATION_REQUIRED = _lib.HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED
    RANGE_NOT_SATISFIABLE = _lib.HTTP_STATUS_RANGE_NOT_SATISFIABLE
    REQUEST_HEADER_FIELDS_TOO_LARGE = _lib.HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE
    REQUEST_TIMEOUT = _lib.HTTP_STATUS_REQUEST_TIMEOUT
    RESET_CONTENT = _lib.HTTP_STATUS_RESET_CONTENT
    SEE_OTHER = _lib.HTTP_STATUS_SEE_OTHER
    SERVER_ERROR = _lib.HTTP_STATUS_SERVER_ERROR
    SERVICE_UNAVAILABLE = _lib.HTTP_STATUS_SERVICE_UNAVAILABLE
    SWITCHING_PROTOCOLS = _lib.HTTP_STATUS_SWITCHING_PROTOCOLS
    TEMPORARY_REDIRECT = _lib.HTTP_STATUS_TEMPORARY_REDIRECT
    TOO_EARLY = _lib.HTTP_STATUS_TOO_EARLY
    TOO_MANY_REQUESTS = _lib.HTTP_STATUS_TOO_MANY_REQUESTS
    UNAUTHORIZED = _lib.HTTP_STATUS_UNAUTHORIZED
    UNAVAILABLE_FOR_LEGAL_REASONS = _lib.HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS
    UNPROCESSABLE_CONTENT = _lib.HTTP_STATUS_UNPROCESSABLE_CONTENT
    UNSUPPORTED_MEDIA_TYPE = _lib.HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE
    UPGRADE_REQUIRED = _lib.HTTP_STATUS_UPGRADE_REQUIRED
    URI_TOO_LONG = _lib.HTTP_STATUS_URI_TOO_LONG
    USE_PROXY = _lib.HTTP_STATUS_USE_PROXY

    def __str__(self):
        return _bytes_to_value(_lib.httpStatusString(self.value))


class HttpState(IntFlag):
    CONNECT = _lib.HTTP_STATE_CONNECT
    COPY = _lib.HTTP_STATE_COPY
    COPY_SEND = _lib.HTTP_STATE_COPY_SEND
    DELETE = _lib.HTTP_STATE_DELETE
    DELETE_SEND = _lib.HTTP_STATE_DELETE_SEND
    ERROR = _lib.HTTP_STATE_ERROR
    GET = _lib.HTTP_STATE_GET
    GET_SEND = _lib.HTTP_STATE_GET_SEND
    HEAD = _lib.HTTP_STATE_HEAD
    LOCK = _lib.HTTP_STATE_LOCK
    LOCK_RECV = _lib.HTTP_STATE_LOCK_RECV
    LOCK_SEND = _lib.HTTP_STATE_LOCK_SEND
    MKCOL = _lib.HTTP_STATE_MKCOL
    MOVE = _lib.HTTP_STATE_MOVE
    MOVE_SEND = _lib.HTTP_STATE_MOVE_SEND
    OPTIONS = _lib.HTTP_STATE_OPTIONS
    POST = _lib.HTTP_STATE_POST
    POST_RECV = _lib.HTTP_STATE_POST_RECV
    POST_SEND = _lib.HTTP_STATE_POST_SEND
    PROPFIND = _lib.HTTP_STATE_PROPFIND
    PROPFIND_RECV = _lib.HTTP_STATE_PROPFIND_RECV
    PROPFIND_SEND = _lib.HTTP_STATE_PROPFIND_SEND
    PROPPATCH = _lib.HTTP_STATE_PROPPATCH
    PROPPATCH_RECV = _lib.HTTP_STATE_PROPPATCH_RECV
    PROPPATCH_SEND = _lib.HTTP_STATE_PROPPATCH_SEND
    PUT = _lib.HTTP_STATE_PUT
    PUT_RECV = _lib.HTTP_STATE_PUT_RECV
    STATUS = _lib.HTTP_STATE_STATUS
    TRACE = _lib.HTTP_STATE_TRACE
    UNKNOWN_METHOD = _lib.HTTP_STATE_UNKNOWN_METHOD
    UNKNOWN_VERSION = _lib.HTTP_STATE_UNKNOWN_VERSION
    UNLOCK = _lib.HTTP_STATE_UNLOCK
    WAITING = _lib.HTTP_STATE_WAITING

    def __str__(self):
        return _bytes_to_value(_lib.httpStateString(self.value))


class HttpField(IntFlag):
    ACCEPT = _lib.HTTP_FIELD_ACCEPT
    ACCEPT_CH = _lib.HTTP_FIELD_ACCEPT_CH
    ACCEPT_ENCODING = _lib.HTTP_FIELD_ACCEPT_ENCODING
    ACCEPT_LANGUAGE = _lib.HTTP_FIELD_ACCEPT_LANGUAGE
    ACCEPT_RANGES = _lib.HTTP_FIELD_ACCEPT_RANGES
    ACCESS_CONTROL_ALLOW_CREDENTIALS = _lib.HTTP_FIELD_ACCESS_CONTROL_ALLOW_CREDENTIALS
    ACCESS_CONTROL_ALLOW_HEADERS = _lib.HTTP_FIELD_ACCESS_CONTROL_ALLOW_HEADERS
    ACCESS_CONTROL_ALLOW_METHODS = _lib.HTTP_FIELD_ACCESS_CONTROL_ALLOW_METHODS
    ACCESS_CONTROL_ALLOW_ORIGIN = _lib.HTTP_FIELD_ACCESS_CONTROL_ALLOW_ORIGIN
    ACCESS_CONTROL_EXPOSE_HEADERS = _lib.HTTP_FIELD_ACCESS_CONTROL_EXPOSE_HEADERS
    ACCESS_CONTROL_MAX_AGE = _lib.HTTP_FIELD_ACCESS_CONTROL_MAX_AGE
    ACCESS_CONTROL_REQUEST_HEADERS = _lib.HTTP_FIELD_ACCESS_CONTROL_REQUEST_HEADERS
    ACCESS_CONTROL_REQUEST_METHOD = _lib.HTTP_FIELD_ACCESS_CONTROL_REQUEST_METHOD
    AGE = _lib.HTTP_FIELD_AGE
    ALLOW = _lib.HTTP_FIELD_ALLOW
    AUTHENTICATION_CONTROL = _lib.HTTP_FIELD_AUTHENTICATION_CONTROL
    AUTHENTICATION_INFO = _lib.HTTP_FIELD_AUTHENTICATION_INFO
    AUTHORIZATION = _lib.HTTP_FIELD_AUTHORIZATION
    CACHE_CONTROL = _lib.HTTP_FIELD_CACHE_CONTROL
    CACHE_STATUS = _lib.HTTP_FIELD_CACHE_STATUS
    CERT_NOT_AFTER = _lib.HTTP_FIELD_CERT_NOT_AFTER
    CERT_NOT_BEFORE = _lib.HTTP_FIELD_CERT_NOT_BEFORE
    CONNECTION = _lib.HTTP_FIELD_CONNECTION
    CONTENT_DISPOSITION = _lib.HTTP_FIELD_CONTENT_DISPOSITION
    CONTENT_ENCODING = _lib.HTTP_FIELD_CONTENT_ENCODING
    CONTENT_LANGUAGE = _lib.HTTP_FIELD_CONTENT_LANGUAGE
    CONTENT_LENGTH = _lib.HTTP_FIELD_CONTENT_LENGTH
    CONTENT_LOCATION = _lib.HTTP_FIELD_CONTENT_LOCATION
    CONTENT_RANGE = _lib.HTTP_FIELD_CONTENT_RANGE
    CONTENT_SECURITY_POLICY = _lib.HTTP_FIELD_CONTENT_SECURITY_POLICY
    CONTENT_SECURITY_POLICY_REPORT_ONLY = (
        _lib.HTTP_FIELD_CONTENT_SECURITY_POLICY_REPORT_ONLY
    )
    CONTENT_TYPE = _lib.HTTP_FIELD_CONTENT_TYPE
    CROSS_ORIGIN_EMBEDDER_POLICY = _lib.HTTP_FIELD_CROSS_ORIGIN_EMBEDDER_POLICY
    CROSS_ORIGIN_EMBEDDER_POLICY_REPORT_ONLY = (
        _lib.HTTP_FIELD_CROSS_ORIGIN_EMBEDDER_POLICY_REPORT_ONLY
    )
    CROSS_ORIGIN_OPENER_POLICY = _lib.HTTP_FIELD_CROSS_ORIGIN_OPENER_POLICY
    CROSS_ORIGIN_OPENER_POLICY_REPORT_ONLY = (
        _lib.HTTP_FIELD_CROSS_ORIGIN_OPENER_POLICY_REPORT_ONLY
    )
    CROSS_ORIGIN_RESOURCE_POLICY = _lib.HTTP_FIELD_CROSS_ORIGIN_RESOURCE_POLICY
    DASL = _lib.HTTP_FIELD_DASL
    DATE = _lib.HTTP_FIELD_DATE
    DAV = _lib.HTTP_FIELD_DAV
    DEPTH = _lib.HTTP_FIELD_DEPTH
    DESTINATION = _lib.HTTP_FIELD_DESTINATION
    ETAG = _lib.HTTP_FIELD_ETAG
    EXPIRES = _lib.HTTP_FIELD_EXPIRES
    FORWARDED = _lib.HTTP_FIELD_FORWARDED
    FROM = _lib.HTTP_FIELD_FROM
    HOST = _lib.HTTP_FIELD_HOST
    IF = _lib.HTTP_FIELD_IF
    IF_MATCH = _lib.HTTP_FIELD_IF_MATCH
    IF_MODIFIED_SINCE = _lib.HTTP_FIELD_IF_MODIFIED_SINCE
    IF_NONE_MATCH = _lib.HTTP_FIELD_IF_NONE_MATCH
    IF_RANGE = _lib.HTTP_FIELD_IF_RANGE
    IF_SCHEDULE_TAG_MATCH = _lib.HTTP_FIELD_IF_SCHEDULE_TAG_MATCH
    IF_UNMODIFIED_SINCE = _lib.HTTP_FIELD_IF_UNMODIFIED_SINCE
    KEEP_ALIVE = _lib.HTTP_FIELD_KEEP_ALIVE
    LAST_MODIFIED = _lib.HTTP_FIELD_LAST_MODIFIED
    LINK = _lib.HTTP_FIELD_LINK
    LOCATION = _lib.HTTP_FIELD_LOCATION
    LOCK_TOKEN = _lib.HTTP_FIELD_LOCK_TOKEN
    MAX = _lib.HTTP_FIELD_MAX
    MAX_FORWARDS = _lib.HTTP_FIELD_MAX_FORWARDS
    OPTIONAL_WWW_AUTHENTICATE = _lib.HTTP_FIELD_OPTIONAL_WWW_AUTHENTICATE
    ORIGIN = _lib.HTTP_FIELD_ORIGIN
    OSCORE = _lib.HTTP_FIELD_OSCORE
    OVERWRITE = _lib.HTTP_FIELD_OVERWRITE
    PRAGMA = _lib.HTTP_FIELD_PRAGMA
    PROXY_AUTHENTICATE = _lib.HTTP_FIELD_PROXY_AUTHENTICATE
    PROXY_AUTHENTICATION_INFO = _lib.HTTP_FIELD_PROXY_AUTHENTICATION_INFO
    PROXY_AUTHORIZATION = _lib.HTTP_FIELD_PROXY_AUTHORIZATION
    PROXY_STATUS = _lib.HTTP_FIELD_PROXY_STATUS
    PUBLIC = _lib.HTTP_FIELD_PUBLIC
    RANGE = _lib.HTTP_FIELD_RANGE
    REFERER = _lib.HTTP_FIELD_REFERER
    REFRESH = _lib.HTTP_FIELD_REFRESH
    REPLAY_NONCE = _lib.HTTP_FIELD_REPLAY_NONCE
    RETRY_AFTER = _lib.HTTP_FIELD_RETRY_AFTER
    SCHEDULE_REPLY = _lib.HTTP_FIELD_SCHEDULE_REPLY
    SCHEDULE_TAG = _lib.HTTP_FIELD_SCHEDULE_TAG
    SERVER = _lib.HTTP_FIELD_SERVER
    STRICT_TRANSPORT_SECURITY = _lib.HTTP_FIELD_STRICT_TRANSPORT_SECURITY
    TE = _lib.HTTP_FIELD_TE
    TIMEOUT = _lib.HTTP_FIELD_TIMEOUT
    TRAILER = _lib.HTTP_FIELD_TRAILER
    TRANSFER_ENCODING = _lib.HTTP_FIELD_TRANSFER_ENCODING
    UNKNOWN = _lib.HTTP_FIELD_UNKNOWN
    UPGRADE = _lib.HTTP_FIELD_UPGRADE
    USER_AGENT = _lib.HTTP_FIELD_USER_AGENT
    VARY = _lib.HTTP_FIELD_VARY
    VIA = _lib.HTTP_FIELD_VIA
    WWW_AUTHENTICATE = _lib.HTTP_FIELD_WWW_AUTHENTICATE
    X_CONTENT_OPTIONS = _lib.HTTP_FIELD_X_CONTENT_OPTIONS
    X_FRAME_OPTIONS = _lib.HTTP_FIELD_X_FRAME_OPTIONS

    @classmethod
    def _missing_(cls, value):
        if isinstance(value, str):
            field_value = _lib.httpFieldValue(value.encode())
            return cls(field_value)
        return None


class HttpUriCoding(IntFlag):
    ALL = _lib.HTTP_URI_CODING_ALL
    HOSTNAME = _lib.HTTP_URI_CODING_HOSTNAME
    MOST = _lib.HTTP_URI_CODING_MOST
    NONE = _lib.HTTP_URI_CODING_NONE
    QUERY = _lib.HTTP_URI_CODING_QUERY
    RESOURCE = _lib.HTTP_URI_CODING_RESOURCE
    RFC6874 = _lib.HTTP_URI_CODING_RFC6874
    USERNAME = _lib.HTTP_URI_CODING_USERNAME


class HttpUriStatus(IntFlag):
    BAD_ARGUMENTS = _lib.HTTP_URI_STATUS_BAD_ARGUMENTS
    BAD_HOSTNAME = _lib.HTTP_URI_STATUS_BAD_HOSTNAME
    BAD_PORT = _lib.HTTP_URI_STATUS_BAD_PORT
    BAD_RESOURCE = _lib.HTTP_URI_STATUS_BAD_RESOURCE
    BAD_SCHEME = _lib.HTTP_URI_STATUS_BAD_SCHEME
    BAD_URI = _lib.HTTP_URI_STATUS_BAD_URI
    BAD_USERNAME = _lib.HTTP_URI_STATUS_BAD_USERNAME
    MISSING_RESOURCE = _lib.HTTP_URI_STATUS_MISSING_RESOURCE
    MISSING_SCHEME = _lib.HTTP_URI_STATUS_MISSING_SCHEME
    OK = _lib.HTTP_URI_STATUS_OK
    OVERFLOW = _lib.HTTP_URI_STATUS_OVERFLOW
    UNKNOWN_SCHEME = _lib.HTTP_URI_STATUS_UNKNOWN_SCHEME

    def __str__(self):
        try:
            return _bytes_to_value(_lib.httpUriStatusString(self.value))
        except AttributeError:
            return self.name
