from enum import IntFlag  # noqa: D100

from cups import _cups
from cups.utils import _bytes_to_value

_lib = _cups.lib


class IPPOp(IntFlag):  # noqa: D101
    ACKNOWLEDGE_DOCUMENT = _lib.IPP_OP_ACKNOWLEDGE_DOCUMENT
    ACKNOWLEDGE_ENCRYPTED_JOB_ATTRIBUTES = (
        _lib.IPP_OP_ACKNOWLEDGE_ENCRYPTED_JOB_ATTRIBUTES
    )
    ACKNOWLEDGE_IDENTIFY_PRINTER = _lib.IPP_OP_ACKNOWLEDGE_IDENTIFY_PRINTER
    ACKNOWLEDGE_JOB = _lib.IPP_OP_ACKNOWLEDGE_JOB
    ACTIVATE_PRINTER = _lib.IPP_OP_ACTIVATE_PRINTER
    ADD_DOCUMENT_IMAGES = _lib.IPP_OP_ADD_DOCUMENT_IMAGES
    ALLOCATE_PRINTER_RESOURCES = _lib.IPP_OP_ALLOCATE_PRINTER_RESOURCES
    CANCEL_CURRENT_JOB = _lib.IPP_OP_CANCEL_CURRENT_JOB
    CANCEL_DOCUMENT = _lib.IPP_OP_CANCEL_DOCUMENT
    CANCEL_JOB = _lib.IPP_OP_CANCEL_JOB
    CANCEL_JOBS = _lib.IPP_OP_CANCEL_JOBS
    CANCEL_MY_JOBS = _lib.IPP_OP_CANCEL_MY_JOBS
    CANCEL_RESOURCE = _lib.IPP_OP_CANCEL_RESOURCE
    CANCEL_SUBSCRIPTION = _lib.IPP_OP_CANCEL_SUBSCRIPTION
    CLOSE_JOB = _lib.IPP_OP_CLOSE_JOB
    CREATE_JOB = _lib.IPP_OP_CREATE_JOB
    CREATE_JOB_SUBSCRIPTIONS = _lib.IPP_OP_CREATE_JOB_SUBSCRIPTIONS
    CREATE_PRINTER = _lib.IPP_OP_CREATE_PRINTER
    CREATE_PRINTER_SUBSCRIPTIONS = _lib.IPP_OP_CREATE_PRINTER_SUBSCRIPTIONS
    CREATE_RESOURCE = _lib.IPP_OP_CREATE_RESOURCE
    CREATE_RESOURCE_SUBSCRIPTIONS = _lib.IPP_OP_CREATE_RESOURCE_SUBSCRIPTIONS
    CREATE_SYSTEM_SUBSCRIPTIONS = _lib.IPP_OP_CREATE_SYSTEM_SUBSCRIPTIONS
    CUPS_ACCEPT_JOBS = _lib.IPP_OP_CUPS_ACCEPT_JOBS
    CUPS_ADD_MODIFY_CLASS = _lib.IPP_OP_CUPS_ADD_MODIFY_CLASS
    CUPS_ADD_MODIFY_PRINTER = _lib.IPP_OP_CUPS_ADD_MODIFY_PRINTER
    CUPS_AUTHENTICATE_JOB = _lib.IPP_OP_CUPS_AUTHENTICATE_JOB
    CUPS_CREATE_LOCAL_PRINTER = _lib.IPP_OP_CUPS_CREATE_LOCAL_PRINTER
    CUPS_DELETE_CLASS = _lib.IPP_OP_CUPS_DELETE_CLASS
    CUPS_DELETE_PRINTER = _lib.IPP_OP_CUPS_DELETE_PRINTER
    CUPS_GET_CLASSES = _lib.IPP_OP_CUPS_GET_CLASSES
    CUPS_GET_DEFAULT = _lib.IPP_OP_CUPS_GET_DEFAULT
    CUPS_GET_DEVICES = _lib.IPP_OP_CUPS_GET_DEVICES
    CUPS_GET_DOCUMENT = _lib.IPP_OP_CUPS_GET_DOCUMENT
    CUPS_GET_PPD = _lib.IPP_OP_CUPS_GET_PPD
    CUPS_GET_PPDS = _lib.IPP_OP_CUPS_GET_PPDS
    CUPS_GET_PRINTERS = _lib.IPP_OP_CUPS_GET_PRINTERS
    CUPS_INVALID = _lib.IPP_OP_CUPS_INVALID
    CUPS_MOVE_JOB = _lib.IPP_OP_CUPS_MOVE_JOB
    CUPS_REJECT_JOBS = _lib.IPP_OP_CUPS_REJECT_JOBS
    CUPS_SET_DEFAULT = _lib.IPP_OP_CUPS_SET_DEFAULT
    DEACTIVATE_PRINTER = _lib.IPP_OP_DEACTIVATE_PRINTER
    DEALLOCATE_PRINTER_RESOURCES = _lib.IPP_OP_DEALLOCATE_PRINTER_RESOURCES
    DELETE_DOCUMENT = _lib.IPP_OP_DELETE_DOCUMENT
    DELETE_PRINTER = _lib.IPP_OP_DELETE_PRINTER
    DEREGISTER_OUTPUT_DEVICE = _lib.IPP_OP_DEREGISTER_OUTPUT_DEVICE
    DISABLE_ALL_PRINTERS = _lib.IPP_OP_DISABLE_ALL_PRINTERS
    DISABLE_PRINTER = _lib.IPP_OP_DISABLE_PRINTER
    ENABLE_ALL_PRINTERS = _lib.IPP_OP_ENABLE_ALL_PRINTERS
    ENABLE_PRINTER = _lib.IPP_OP_ENABLE_PRINTER
    FETCH_DOCUMENT = _lib.IPP_OP_FETCH_DOCUMENT
    FETCH_ENCRYPTED_JOB_ATTRIBUTES = _lib.IPP_OP_FETCH_ENCRYPTED_JOB_ATTRIBUTES
    FETCH_JOB = _lib.IPP_OP_FETCH_JOB
    GET_DOCUMENTS = _lib.IPP_OP_GET_DOCUMENTS
    GET_DOCUMENT_ATTRIBUTES = _lib.IPP_OP_GET_DOCUMENT_ATTRIBUTES
    GET_ENCRYPTED_JOB_ATTRIBUTES = _lib.IPP_OP_GET_ENCRYPTED_JOB_ATTRIBUTES
    GET_JOBS = _lib.IPP_OP_GET_JOBS
    GET_JOB_ATTRIBUTES = _lib.IPP_OP_GET_JOB_ATTRIBUTES
    GET_NEXT_DOCUMENT_DATA = _lib.IPP_OP_GET_NEXT_DOCUMENT_DATA
    GET_NOTIFICATIONS = _lib.IPP_OP_GET_NOTIFICATIONS
    GET_OUTPUT_DEVICE_ATTRIBUTES = _lib.IPP_OP_GET_OUTPUT_DEVICE_ATTRIBUTES
    GET_PRINTERS = _lib.IPP_OP_GET_PRINTERS
    GET_PRINTER_ATTRIBUTES = _lib.IPP_OP_GET_PRINTER_ATTRIBUTES
    GET_PRINTER_RESOURCES = _lib.IPP_OP_GET_PRINTER_RESOURCES
    GET_PRINTER_SUPPORTED_VALUES = _lib.IPP_OP_GET_PRINTER_SUPPORTED_VALUES
    GET_PRINT_SUPPORT_FILES = _lib.IPP_OP_GET_PRINT_SUPPORT_FILES
    GET_RESOURCES = _lib.IPP_OP_GET_RESOURCES
    GET_RESOURCE_ATTRIBUTES = _lib.IPP_OP_GET_RESOURCE_ATTRIBUTES
    GET_RESOURCE_DATA = _lib.IPP_OP_GET_RESOURCE_DATA
    GET_SUBSCRIPTIONS = _lib.IPP_OP_GET_SUBSCRIPTIONS
    GET_SUBSCRIPTION_ATTRIBUTES = _lib.IPP_OP_GET_SUBSCRIPTION_ATTRIBUTES
    GET_SYSTEM_ATTRIBUTES = _lib.IPP_OP_GET_SYSTEM_ATTRIBUTES
    GET_SYSTEM_SUPPORTED_VALUES = _lib.IPP_OP_GET_SYSTEM_SUPPORTED_VALUES
    GET_USER_PRINTER_ATTRIBUTES = _lib.IPP_OP_GET_USER_PRINTER_ATTRIBUTES
    HOLD_JOB = _lib.IPP_OP_HOLD_JOB
    HOLD_NEW_JOBS = _lib.IPP_OP_HOLD_NEW_JOBS
    IDENTIFY_PRINTER = _lib.IPP_OP_IDENTIFY_PRINTER
    INSTALL_RESOURCE = _lib.IPP_OP_INSTALL_RESOURCE
    PAUSE_ALL_PRINTERS = _lib.IPP_OP_PAUSE_ALL_PRINTERS
    PAUSE_ALL_PRINTERS_AFTER_CURRENT_JOB = (
        _lib.IPP_OP_PAUSE_ALL_PRINTERS_AFTER_CURRENT_JOB
    )
    PAUSE_PRINTER = _lib.IPP_OP_PAUSE_PRINTER
    PAUSE_PRINTER_AFTER_CURRENT_JOB = _lib.IPP_OP_PAUSE_PRINTER_AFTER_CURRENT_JOB
    PRINT_JOB = _lib.IPP_OP_PRINT_JOB
    PRINT_URI = _lib.IPP_OP_PRINT_URI
    PROMOTE_JOB = _lib.IPP_OP_PROMOTE_JOB
    PURGE_JOBS = _lib.IPP_OP_PURGE_JOBS
    REGISTER_OUTPUT_DEVICE = _lib.IPP_OP_REGISTER_OUTPUT_DEVICE
    RELEASE_HELD_NEW_JOBS = _lib.IPP_OP_RELEASE_HELD_NEW_JOBS
    RELEASE_JOB = _lib.IPP_OP_RELEASE_JOB
    RENEW_SUBSCRIPTION = _lib.IPP_OP_RENEW_SUBSCRIPTION
    REPROCESS_JOB = _lib.IPP_OP_REPROCESS_JOB
    RESTART_JOB = _lib.IPP_OP_RESTART_JOB
    RESTART_ONE_PRINTER = _lib.IPP_OP_RESTART_ONE_PRINTER
    RESTART_PRINTER = _lib.IPP_OP_RESTART_PRINTER
    RESTART_SYSTEM = _lib.IPP_OP_RESTART_SYSTEM
    RESUBMIT_JOB = _lib.IPP_OP_RESUBMIT_JOB
    RESUME_ALL_PRINTERS = _lib.IPP_OP_RESUME_ALL_PRINTERS
    RESUME_JOB = _lib.IPP_OP_RESUME_JOB
    RESUME_PRINTER = _lib.IPP_OP_RESUME_PRINTER
    SCHEDULE_JOB_AFTER = _lib.IPP_OP_SCHEDULE_JOB_AFTER
    SEND_DOCUMENT = _lib.IPP_OP_SEND_DOCUMENT
    SEND_NOTIFICATIONS = _lib.IPP_OP_SEND_NOTIFICATIONS
    SEND_RESOURCE_DATA = _lib.IPP_OP_SEND_RESOURCE_DATA
    SEND_URI = _lib.IPP_OP_SEND_URI
    SET_DOCUMENT_ATTRIBUTES = _lib.IPP_OP_SET_DOCUMENT_ATTRIBUTES
    SET_JOB_ATTRIBUTES = _lib.IPP_OP_SET_JOB_ATTRIBUTES
    SET_PRINTER_ATTRIBUTES = _lib.IPP_OP_SET_PRINTER_ATTRIBUTES
    SET_RESOURCE_ATTRIBUTES = _lib.IPP_OP_SET_RESOURCE_ATTRIBUTES
    SET_SYSTEM_ATTRIBUTES = _lib.IPP_OP_SET_SYSTEM_ATTRIBUTES
    SHUTDOWN_ALL_PRINTERS = _lib.IPP_OP_SHUTDOWN_ALL_PRINTERS
    SHUTDOWN_ONE_PRINTER = _lib.IPP_OP_SHUTDOWN_ONE_PRINTER
    SHUTDOWN_PRINTER = _lib.IPP_OP_SHUTDOWN_PRINTER
    STARTUP_ALL_PRINTERS = _lib.IPP_OP_STARTUP_ALL_PRINTERS
    STARTUP_ONE_PRINTER = _lib.IPP_OP_STARTUP_ONE_PRINTER
    STARTUP_PRINTER = _lib.IPP_OP_STARTUP_PRINTER
    SUSPEND_CURRENT_JOB = _lib.IPP_OP_SUSPEND_CURRENT_JOB
    UPDATE_ACTIVE_JOBS = _lib.IPP_OP_UPDATE_ACTIVE_JOBS
    UPDATE_DOCUMENT_STATUS = _lib.IPP_OP_UPDATE_DOCUMENT_STATUS
    UPDATE_JOB_STATUS = _lib.IPP_OP_UPDATE_JOB_STATUS
    UPDATE_OUTPUT_DEVICE_ATTRIBUTES = _lib.IPP_OP_UPDATE_OUTPUT_DEVICE_ATTRIBUTES
    VALIDATE_DOCUMENT = _lib.IPP_OP_VALIDATE_DOCUMENT
    VALIDATE_JOB = _lib.IPP_OP_VALIDATE_JOB

    def __str__(self) -> str:
        return _bytes_to_value(_lib.ippOpString(self.value))  # type: ignore[return-value]

    @classmethod
    def _missing_(cls, value):  # noqa: ANN001, ANN206
        if isinstance(value, str):
            op = _lib.ippOpValue(value.encode())
            return cls(op)
        return None


class IPPTag(IntFlag):  # noqa: D101
    ADMINDEFINE = _lib.IPP_TAG_ADMINDEFINE
    BEGIN_COLLECTION = _lib.IPP_TAG_BEGIN_COLLECTION
    BOOLEAN = _lib.IPP_TAG_BOOLEAN
    CHARSET = _lib.IPP_TAG_CHARSET
    CUPS_CONST = _lib.IPP_TAG_CUPS_CONST
    CUPS_INVALID = _lib.IPP_TAG_CUPS_INVALID
    CUPS_MASK = _lib.IPP_TAG_CUPS_MASK
    DATE = _lib.IPP_TAG_DATE
    DEFAULT = _lib.IPP_TAG_DEFAULT
    DELETEATTR = _lib.IPP_TAG_DELETEATTR
    DOCUMENT = _lib.IPP_TAG_DOCUMENT
    END = _lib.IPP_TAG_END
    END_COLLECTION = _lib.IPP_TAG_END_COLLECTION
    ENUM = _lib.IPP_TAG_ENUM
    EVENT_NOTIFICATION = _lib.IPP_TAG_EVENT_NOTIFICATION
    EXTENSION = _lib.IPP_TAG_EXTENSION
    INTEGER = _lib.IPP_TAG_INTEGER
    JOB = _lib.IPP_TAG_JOB
    KEYWORD = _lib.IPP_TAG_KEYWORD
    LANGUAGE = _lib.IPP_TAG_LANGUAGE
    MEMBERNAME = _lib.IPP_TAG_MEMBERNAME
    MIMETYPE = _lib.IPP_TAG_MIMETYPE
    NAME = _lib.IPP_TAG_NAME
    NAMELANG = _lib.IPP_TAG_NAMELANG
    NOTSETTABLE = _lib.IPP_TAG_NOTSETTABLE
    NOVALUE = _lib.IPP_TAG_NOVALUE
    OPERATION = _lib.IPP_TAG_OPERATION
    PRINTER = _lib.IPP_TAG_PRINTER
    RANGE = _lib.IPP_TAG_RANGE
    RESOLUTION = _lib.IPP_TAG_RESOLUTION
    RESOURCE = _lib.IPP_TAG_RESOURCE
    STRING = _lib.IPP_TAG_STRING
    SUBSCRIPTION = _lib.IPP_TAG_SUBSCRIPTION
    SYSTEM = _lib.IPP_TAG_SYSTEM
    TEXT = _lib.IPP_TAG_TEXT
    TEXTLANG = _lib.IPP_TAG_TEXTLANG
    UNKNOWN = _lib.IPP_TAG_UNKNOWN
    UNSUPPORTED_GROUP = _lib.IPP_TAG_UNSUPPORTED_GROUP
    UNSUPPORTED_VALUE = _lib.IPP_TAG_UNSUPPORTED_VALUE
    URI = _lib.IPP_TAG_URI
    URISCHEME = _lib.IPP_TAG_URISCHEME
    ZERO = _lib.IPP_TAG_ZERO


class IPPState(IntFlag):  # noqa: D101
    ATTRIBUTE = _lib.IPP_STATE_ATTRIBUTE
    DATA = _lib.IPP_STATE_DATA
    ERROR = _lib.IPP_STATE_ERROR
    HEADER = _lib.IPP_STATE_HEADER
    IDLE = _lib.IPP_STATE_IDLE


class IPPStatus(IntFlag):  # noqa: D101
    CUPS_INVALID = _lib.IPP_STATUS_CUPS_INVALID
    ERROR_ACCOUNT_AUTHORIZATION_FAILED = (
        _lib.IPP_STATUS_ERROR_ACCOUNT_AUTHORIZATION_FAILED
    )
    ERROR_ACCOUNT_CLOSED = _lib.IPP_STATUS_ERROR_ACCOUNT_CLOSED
    ERROR_ACCOUNT_INFO_NEEDED = _lib.IPP_STATUS_ERROR_ACCOUNT_INFO_NEEDED
    ERROR_ACCOUNT_LIMIT_REACHED = _lib.IPP_STATUS_ERROR_ACCOUNT_LIMIT_REACHED
    ERROR_ATTRIBUTES_NOT_SETTABLE = _lib.IPP_STATUS_ERROR_ATTRIBUTES_NOT_SETTABLE
    ERROR_ATTRIBUTES_OR_VALUES = _lib.IPP_STATUS_ERROR_ATTRIBUTES_OR_VALUES
    ERROR_BAD_REQUEST = _lib.IPP_STATUS_ERROR_BAD_REQUEST
    ERROR_BUSY = _lib.IPP_STATUS_ERROR_BUSY
    ERROR_CHARSET = _lib.IPP_STATUS_ERROR_CHARSET
    ERROR_COMPRESSION_ERROR = _lib.IPP_STATUS_ERROR_COMPRESSION_ERROR
    ERROR_COMPRESSION_NOT_SUPPORTED = _lib.IPP_STATUS_ERROR_COMPRESSION_NOT_SUPPORTED
    ERROR_CONFLICTING = _lib.IPP_STATUS_ERROR_CONFLICTING
    ERROR_CUPS_AUTHENTICATION_CANCELED = (
        _lib.IPP_STATUS_ERROR_CUPS_AUTHENTICATION_CANCELED
    )
    ERROR_CUPS_OAUTH = _lib.IPP_STATUS_ERROR_CUPS_OAUTH
    ERROR_CUPS_PKI = _lib.IPP_STATUS_ERROR_CUPS_PKI
    ERROR_CUPS_UPGRADE_REQUIRED = _lib.IPP_STATUS_ERROR_CUPS_UPGRADE_REQUIRED
    ERROR_DEVICE = _lib.IPP_STATUS_ERROR_DEVICE
    ERROR_DOCUMENT_ACCESS = _lib.IPP_STATUS_ERROR_DOCUMENT_ACCESS
    ERROR_DOCUMENT_FORMAT_ERROR = _lib.IPP_STATUS_ERROR_DOCUMENT_FORMAT_ERROR
    ERROR_DOCUMENT_FORMAT_NOT_SUPPORTED = (
        _lib.IPP_STATUS_ERROR_DOCUMENT_FORMAT_NOT_SUPPORTED
    )
    ERROR_DOCUMENT_PASSWORD = _lib.IPP_STATUS_ERROR_DOCUMENT_PASSWORD
    ERROR_DOCUMENT_PERMISSION = _lib.IPP_STATUS_ERROR_DOCUMENT_PERMISSION
    ERROR_DOCUMENT_SECURITY = _lib.IPP_STATUS_ERROR_DOCUMENT_SECURITY
    ERROR_DOCUMENT_UNPRINTABLE = _lib.IPP_STATUS_ERROR_DOCUMENT_UNPRINTABLE
    ERROR_FORBIDDEN = _lib.IPP_STATUS_ERROR_FORBIDDEN
    ERROR_GONE = _lib.IPP_STATUS_ERROR_GONE
    ERROR_IGNORED_ALL_SUBSCRIPTIONS = _lib.IPP_STATUS_ERROR_IGNORED_ALL_SUBSCRIPTIONS
    ERROR_INTERNAL = _lib.IPP_STATUS_ERROR_INTERNAL
    ERROR_JOB_CANCELED = _lib.IPP_STATUS_ERROR_JOB_CANCELED
    ERROR_MULTIPLE_JOBS_NOT_SUPPORTED = (
        _lib.IPP_STATUS_ERROR_MULTIPLE_JOBS_NOT_SUPPORTED
    )
    ERROR_NOT_ACCEPTING_JOBS = _lib.IPP_STATUS_ERROR_NOT_ACCEPTING_JOBS
    ERROR_NOT_AUTHENTICATED = _lib.IPP_STATUS_ERROR_NOT_AUTHENTICATED
    ERROR_NOT_AUTHORIZED = _lib.IPP_STATUS_ERROR_NOT_AUTHORIZED
    ERROR_NOT_FETCHABLE = _lib.IPP_STATUS_ERROR_NOT_FETCHABLE
    ERROR_NOT_FOUND = _lib.IPP_STATUS_ERROR_NOT_FOUND
    ERROR_NOT_POSSIBLE = _lib.IPP_STATUS_ERROR_NOT_POSSIBLE
    ERROR_OPERATION_NOT_SUPPORTED = _lib.IPP_STATUS_ERROR_OPERATION_NOT_SUPPORTED
    ERROR_PRINTER_IS_DEACTIVATED = _lib.IPP_STATUS_ERROR_PRINTER_IS_DEACTIVATED
    ERROR_REQUEST_ENTITY = _lib.IPP_STATUS_ERROR_REQUEST_ENTITY
    ERROR_REQUEST_VALUE = _lib.IPP_STATUS_ERROR_REQUEST_VALUE
    ERROR_SERVICE_UNAVAILABLE = _lib.IPP_STATUS_ERROR_SERVICE_UNAVAILABLE
    ERROR_TEMPORARY = _lib.IPP_STATUS_ERROR_TEMPORARY
    ERROR_TIMEOUT = _lib.IPP_STATUS_ERROR_TIMEOUT
    ERROR_TOO_MANY_DOCUMENTS = _lib.IPP_STATUS_ERROR_TOO_MANY_DOCUMENTS
    ERROR_TOO_MANY_JOBS = _lib.IPP_STATUS_ERROR_TOO_MANY_JOBS
    ERROR_TOO_MANY_SUBSCRIPTIONS = _lib.IPP_STATUS_ERROR_TOO_MANY_SUBSCRIPTIONS
    ERROR_URI_SCHEME = _lib.IPP_STATUS_ERROR_URI_SCHEME
    ERROR_VERSION_NOT_SUPPORTED = _lib.IPP_STATUS_ERROR_VERSION_NOT_SUPPORTED
    OK = _lib.IPP_STATUS_OK
    OK_CONFLICTING = _lib.IPP_STATUS_OK_CONFLICTING
    OK_EVENTS_COMPLETE = _lib.IPP_STATUS_OK_EVENTS_COMPLETE
    OK_IGNORED_OR_SUBSTITUTED = _lib.IPP_STATUS_OK_IGNORED_OR_SUBSTITUTED
    OK_IGNORED_SUBSCRIPTIONS = _lib.IPP_STATUS_OK_IGNORED_SUBSCRIPTIONS
    OK_TOO_MANY_EVENTS = _lib.IPP_STATUS_OK_TOO_MANY_EVENTS


class IPPRes(IntFlag):  # noqa: D101
    CM = _lib.IPP_RES_PER_CM
    INCH = _lib.IPP_RES_PER_INCH
