typedef struct _cups_array_s cups_array_t;
typedef int (*cups_array_cb_t)(void *first, void *second, void *data);
typedef size_t (*cups_ahash_cb_t)(void *element, void *data);
typedef void *(*cups_acopy_cb_t)(void *element, void *data);
typedef void (*cups_afree_cb_t)(void *element, void *data);
bool		cupsArrayAdd(cups_array_t *a, void *e);
bool		cupsArrayAddStrings(cups_array_t *a, const char *s, char delim);
void		cupsArrayClear(cups_array_t *a);
void		cupsArrayDelete(cups_array_t *a);
cups_array_t	*cupsArrayDup(cups_array_t *a);
void		*cupsArrayFind(cups_array_t *a, void *e);
size_t		cupsArrayGetCount(cups_array_t *a);
void		*cupsArrayGetCurrent(cups_array_t *a);
void		*cupsArrayGetElement(cups_array_t *a, size_t n);
void		*cupsArrayGetFirst(cups_array_t *a);
size_t		cupsArrayGetIndex(cups_array_t *a);
size_t		cupsArrayGetInsert(cups_array_t *a);
void		*cupsArrayGetLast(cups_array_t *a);
void		*cupsArrayGetNext(cups_array_t *a);
void		*cupsArrayGetPrev(cups_array_t *a);
void		*cupsArrayGetUserData(cups_array_t *a);
bool		cupsArrayInsert(cups_array_t *a, void *e);
cups_array_t	*cupsArrayNew(cups_array_cb_t f, void *d, cups_ahash_cb_t hf, size_t hsize, cups_acopy_cb_t cf, cups_afree_cb_t ff);
cups_array_t	*cupsArrayNewStrings(const char *s, char delim);
bool		cupsArrayRemove(cups_array_t *a, void *e);
void		*cupsArrayRestore(cups_array_t *a);
bool		cupsArraySave(cups_array_t *a);
