typedef int... off_t;
typedef struct _cups_file_s cups_file_t;
bool		cupsFileClose(cups_file_t *fp);
bool		cupsFileEOF(cups_file_t *fp);
const char	*cupsFileFind(const char *filename, const char *path, bool executable, char *buffer, size_t bufsize);
bool		cupsFileFlush(cups_file_t *fp);
int		cupsFileGetChar(cups_file_t *fp);
char		*cupsFileGetConf(cups_file_t *fp, char *buf, size_t buflen, char **value, int *linenum);
size_t		cupsFileGetLine(cups_file_t *fp, char *buf, size_t buflen);
char		*cupsFileGets(cups_file_t *fp, char *buf, size_t buflen);
bool		cupsFileIsCompressed(cups_file_t *fp);
bool		cupsFileLock(cups_file_t *fp, bool block);
int		cupsFileNumber(cups_file_t *fp);
cups_file_t	*cupsFileOpen(const char *filename, const char *mode);
cups_file_t	*cupsFileOpenFd(int fd, const char *mode);
int		cupsFilePeekChar(cups_file_t *fp);
bool		cupsFilePrintf(cups_file_t *fp, const char *format, ...);
bool		cupsFilePutChar(cups_file_t *fp, int c);
bool		cupsFilePutConf(cups_file_t *fp, const char *directive, const char *value);
bool		cupsFilePuts(cups_file_t *fp, const char *s);
ssize_t		cupsFileRead(cups_file_t *fp, char *buf, size_t bytes);
off_t		cupsFileRewind(cups_file_t *fp);
off_t		cupsFileSeek(cups_file_t *fp, off_t pos);
cups_file_t	*cupsFileStderr(void);
cups_file_t	*cupsFileStdin(void);
cups_file_t	*cupsFileStdout(void);
off_t		cupsFileTell(cups_file_t *fp);
bool		cupsFileUnlock(cups_file_t *fp);
bool		cupsFileWrite(cups_file_t *fp, const char *buf, size_t bytes);
