typedef void *(__stdcall *cups_thread_func_t)(void *arg);
typedef struct _cups_thread_s *cups_thread_t;
typedef CONDITION_VARIABLE cups_cond_t;	
typedef CRITICAL_SECTION cups_mutex_t;	
typedef SRWLOCK cups_rwlock_t;		
typedef DWORD	cups_thread_key_t;	
typedef void *(*cups_thread_func_t)(void *arg);
typedef pthread_t cups_thread_t;	
typedef pthread_cond_t cups_cond_t;	
typedef pthread_mutex_t cups_mutex_t;	
typedef pthread_rwlock_t cups_rwlock_t;	
typedef pthread_key_t	cups_thread_key_t;
void	cupsCondBroadcast(cups_cond_t *cond);
void	cupsCondDestroy(cups_cond_t *cond);
void	cupsCondInit(cups_cond_t *cond);
void	cupsCondWait(cups_cond_t *cond, cups_mutex_t *mutex, double timeout);
void	cupsMutexDestroy(cups_mutex_t *mutex);
void	cupsMutexInit(cups_mutex_t *mutex);
void	cupsMutexLock(cups_mutex_t *mutex);
void	cupsMutexUnlock(cups_mutex_t *mutex);
void	cupsRWDestroy(cups_rwlock_t *rwlock);
void	cupsRWInit(cups_rwlock_t *rwlock);
void	cupsRWLockRead(cups_rwlock_t *rwlock);
void	cupsRWLockWrite(cups_rwlock_t *rwlock);
void	cupsRWUnlock(cups_rwlock_t *rwlock);
void	cupsThreadCancel(cups_thread_t thread);
cups_thread_t cupsThreadCreate(cups_thread_func_t func, void *arg);
void     cupsThreadDetach(cups_thread_t thread);
void	*cupsThreadWait(cups_thread_t thread);
